/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-06-12 01:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/common/head.jsp", Long.valueOf(1528712144770L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/common/common.css");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readVerNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/common/reset.css");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readVerNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/common/title.css");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readVerNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/common/dialog.css");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readVerNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common/common.js?v=6\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common/jr.js?v=2\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction toIndexJsp() {\r\n");
      out.write("\t\tlocation.href = \"/index.do\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goBack() {\r\n");
      out.write("\t\tlocation.href = \"javascript:history.go(-1);\"\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction forIE6() {\r\n");
      out.write("\t\tvar bar = getBow();\r\n");
      out.write("\t\tif (bar == 'IE6') {\r\n");
      out.write("\t\t\t$('#forIe6Div').dialog('open', {\r\n");
      out.write("\t\t\t\turl : 'jsp/updateIE.html',\r\n");
      out.write("\t\t\t\ttitle : '更新浏览器',\r\n");
      out.write("\t\t\t\tneedClose : false,\r\n");
      out.write("\t\t\t\twidth : '600',\r\n");
      out.write("\t\t\t\theight : '200'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkIsLogin(needInfo) {\r\n");
      out.write("\t\tusrFlag = localStorage.usrFlag;\r\n");
      out.write("\t\tisLogin = false;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/ajax/check.do',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tcheckKey : usrFlag\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tob = eval('(' + data + ')');\r\n");
      out.write("\t\t\t\tif (ob.result == 'success') {\r\n");
      out.write("\t\t\t\t\tisLogin = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif (!needInfo) {\r\n");
      out.write("\t\t\t\t\t\t$.message.alert(\"info\", \"提示\", \"用户未登录，将跳转至登录页\",\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation.href = \"/loginHome.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tisLogin = false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"/loginHome.do\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\treturn isLogin;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkVipLevel(bookId) {\r\n");
      out.write("\t\tusrFlag = localStorage.usrFlag;\r\n");
      out.write("\t\tconformToVip = false;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/book/ajax/checkVipLevel.do',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tcheckKey : usrFlag,\r\n");
      out.write("\t\t\t\tbookId : bookId\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tob = eval('(' + data + ')');\r\n");
      out.write("\t\t\t\tif (ob.result == '0') {\r\n");
      out.write("\t\t\t\t\tconformToVip = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.message.alert('info', '提示', ob.msg, function() {\r\n");
      out.write("\t\t\t\t\t\tlocation.href = '/pay/payPage.do?checkKey='+usrFlag+'&bookId='+bookId;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tconformToVip = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\treturn conformToVip;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<html style=\"font-size: 50px;\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"-1\">\r\n");
      out.write("<meta content=\"yes\" name=\"apple-mobile-web-app-capable\">\r\n");
      out.write("<meta content=\"yes\" name=\"apple-touch-fullscreen\">\r\n");
      out.write("<meta content=\"black\" name=\"apple-mobile-web-app-status-bar-style\">\r\n");
      out.write("<meta content=\"telephone=no, email=no\" name=\"format-detection\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/classify.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/index.css\" type=\"text/css\">\r\n");
      out.write("<title>17K</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"codeHide\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"tabIdHide\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"isHomeHide\" value=\"1\">\r\n");
      out.write("\t<div class='head-parent'>\r\n");
      out.write("\t\t<div class=\"my_head fc my_head-home\">\r\n");
      out.write("\t\t\t<div class=\"fl fc\">\r\n");
      out.write("\t\t\t\t<i class=\"home_logo fl\"> </i>\r\n");
      out.write("\t\t\t\t<div class=\"my_title fl\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mh_right fr\">\r\n");
      out.write("\t\t\t\t<div class=\"my_person fr\" onclick=\"checkIsLogin('notNeed');\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/person@2x.png\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--频道选择-->\r\n");
      out.write("\t<div class=\"my_nav fc\">\r\n");
      out.write("\t\t<ul class=\"myul\"></ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"my_foot\">\r\n");
      out.write("\t\t<div class=\"nav_search\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"搜索\" id=\"footSearchInput\" />\r\n");
      out.write("\t\t\t<div class=\"ns_img\" onclick=\"serachBook();\">\r\n");
      out.write("\t\t\t\t<img src=\"/images/search.png\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- home页面的 '最近阅读' 与 '书架' -->\r\n");
      out.write("\t<div style=\"background-color: #d26c3129\">\r\n");
      out.write("\t\t<div class=\"my_record\">\r\n");
      out.write("\t\t\t<div class=\"my_record_recent\">\r\n");
      out.write("\t\t\t\t<div class=\"mr_img_left\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/record@2x.png\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"my_r_name\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"my_record_shift\">\r\n");
      out.write("\t\t\t\t<div class=\"shu_line\"></div>\r\n");
      out.write("\t\t\t\t<img class=\"mr_img_right\" src=\"/images/bookshelft.png\" /> <span\r\n");
      out.write("\t\t\t\t\tid=\"toMyCollect\" class=\"my_r_text\">书架</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"all_content\">\r\n");
      out.write("\t\t<div id=\"moreDiv\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" onclick=\"appendContent()\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar tabList;\r\n");
      out.write("\tvar IndexBookPerPageItem=10;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tinit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tlocalStorage.removeItem(\"flagCat\");\r\n");
      out.write("\t\tinitVipLabel();\r\n");
      out.write("\t\tappendContent();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction initVipLabel() {\r\n");
      out.write("\t\t$('.my_title').html(\"17K\");\r\n");
      out.write("\t\ttabList = new Array({\r\n");
      out.write("\t\t\t'id' : 1,\r\n");
      out.write("\t\t\t'name' : '初级会员'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t'id' : 2,\r\n");
      out.write("\t\t\t'name' : '中级会员 '\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t'id' : 3,\r\n");
      out.write("\t\t\t'name' : '高级会员'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar html = '';\r\n");
      out.write("\t\tfor (var i = 0, lg = tabList.length; i < lg; i++) {\r\n");
      out.write("\t\t\thtml += '<li class=\"tab' + tabList[i].id + '\">' + '<a id=\"tab'\r\n");
      out.write("\t\t\t\t\t+ tabList[i].id + '\" onclick=\"toListHome(' + tabList[i].id\r\n");
      out.write("\t\t\t\t\t+ ')\">'\r\n");
      out.write("\t\t\t\t\t// html += '<li class=\"tab'+tabList[i].id+'\">' + '<span\r\n");
      out.write("\t\t\t\t\t// class=\"nav-top\" id=\"tab'+tabList[i].id +'\"\r\n");
      out.write("\t\t\t\t\t// onclick=\"toHome(' + tabList[i].id + ')\">'\r\n");
      out.write("\t\t\t\t\t+ tabList[i].name + '</span></li>';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// html += '<li id=\"toPayBeanBtn\"><a>充值</a></li>';\r\n");
      out.write("\t\t$('.my_nav .myul').append(html);\r\n");
      out.write("\t\t$('.foot_nav .myul').append(html);\r\n");
      out.write("\t\twrapTab();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction toListHome(tabId) {\r\n");
      out.write("\t\twindow.location.href = '/index/' + tabId + \".do\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction wrapTab() {\r\n");
      out.write("\t\tvar tabId = null;\r\n");
      out.write("\t\ttabId = $(\"#tabIdHide\").val();\r\n");
      out.write("\t\tif (null == tabId || '' == tabId) {\r\n");
      out.write("\t\t\ttabId = tabList[0].id;\r\n");
      out.write("\t\t\tif (null != tabId) {\r\n");
      out.write("\t\t\t\t$(\"#tabIdHide\").val(tabId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (null == tabId || '' == tabId) {\r\n");
      out.write("\t\t\talert(\"无法获取当前频道信息\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\".my_nav li\").removeClass('nv_active');\r\n");
      out.write("\t\t$(\".tab\" + tabId).addClass('nv_active');\r\n");
      out.write("\t\t$(\"#tab\" + tabId).css(\"width\", \"1.5rem\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction appendContent(currentPage, totalCount) {\r\n");
      out.write("\t\ttabId = $('#tabIdHide').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\turl : '/index/ajax/books.do',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tvipLevel : tabId,\r\n");
      out.write("\t\t\t\tcurrentPage : currentPage,\r\n");
      out.write("\t\t\t\titemPerPage : IndexBookPerPageItem,\r\n");
      out.write("\t\t\t\ttotalCount : totalCount\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\t\tvar moreDiv = $('#moreDiv');\r\n");
      out.write("\t\t\t\tif (moreDiv) {\r\n");
      out.write("\t\t\t\t\tmoreDiv.remove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('.all_content').append(obj);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction serachBook() {\r\n");
      out.write("\t\tvar bookName = $('#footSearchInput').val();\r\n");
      out.write("\t\tif (!bookName || bookName == '') {\r\n");
      out.write("\t\t\tappendContent();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\turl : '/index/ajax/bookInfo.do',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'bookName' : bookName,\r\n");
      out.write("\t\t\t\t'vipLevel':$('#tabIdHide').val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\t\t$('.all_content').empty();\r\n");
      out.write("\t\t\t\t$('.all_content').append(obj);\r\n");
      out.write("\t\t\t\tvar moreDiv = $('#moreDiv');\r\n");
      out.write("\t\t\t\tif (moreDiv) {\r\n");
      out.write("\t\t\t\t\tmoreDiv.remove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
